### ISSUE TITLE
Error in strsplit(tables[[2]][1, 1], "Page 1 of ") : non-character argument

### ISSUE THREAD

**Issue by s1nisteR** [robjhyndman/cricketdata#14]
I tried the code
```R
# Load cricketdata
library(tidyverse)
library(cricketdata)

# Fetch men's T20 batting data 
mt20 <- fetch_cricinfo("T20", "Men", "Batting")

# Filter for only Australia and India
mt20_aus_ind <- mt20 %>%
  filter(Country %in% c("India", "Australia"))

```

The line
```R
mt20 <- fetch_cricinfo("T20", "Men", "Batting")
```
raises the error. Kindly help me out with it.

**Comment by smanaseer** [comment]
I think it is line 73 in fetch_cricket_data.R. I am having the same issue here.

**Comment by tooba-jd** [comment]
I got the same issue and I fixed it in the follow way:

I tried to make the URL and see what the issue is y myself. I solved the issue by adding function 'as.charcter' to line 73 of fetch_cricket_data.R. You need to use as.numeric(strsplit(**as.character**(tables[[2]][1,1]), "Page 1 of ")[[1]][2]) instead of as.numeric(strsplit(tables[[2]][1,1], "Page 1 of ")[[1]][2])

Moreover, I set the choices whenever the function "match.arg" is used. So I searched for "match.arg" and replaced it by adding the choices. Following is an example:
matchtype <- match.arg(matchtype**,choices = c( "t20","test", "odi"**))
